# Generated by Django 5.2.7 on 2025-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField(blank=True, db_column='HireDate', null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(db_column='GenreID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'Genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(db_column='HallID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('capacity', models.PositiveIntegerField(db_column='Capacity')),
                ('type', models.CharField(db_column='Type', max_length=30)),
            ],
            options={
                'db_table': 'Hall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('position_id', models.AutoField(db_column='PositionID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'JobPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('duration', models.PositiveIntegerField(db_column='Duration')),
                ('age_limit', models.PositiveIntegerField(db_column='AgeLimit')),
                ('release_year', models.PositiveIntegerField(db_column='ReleaseYear')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'Movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(db_column='SessionID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='StartTime')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('seat_number', models.PositiveIntegerField(db_column='SeatNumber')),
                ('purchase_date', models.DecimalField(db_column='PurchaseDate', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': False,
            },
        ),
    ]
